### ISSUE TITLE
Experimental fractional scaling doesn't work - Ubuntu 19.04 + Regolight desktop

### ISSUE THREAD

**Issue by fourstepper** [regolith-linux/regolith-gnome-flashback#2]
Hello, I love this spin add-on upon Ubuntu and everything works properly except the fractional display scaling. Right now I've just lowered the resolution which is fine anyway for my use, just wanted to let you know about this and would love to know why there might be a problem with this. 

I followed this guide: https://www.linuxuprising.com/2019/04/how-to-enable-hidpi-fractional-scaling.html

**Comment by kgilmer** [comment]
Hi @Fourstepper ! I took a look at your link and the settings described seem specific to the Gnome window manager, Mutter.  Because Regolith uses i3-gaps, those settings would not have an effect.  However, I believe you can adjust the scaling by specifying your DPI via Xresources.  For example, `~/.Xresources`:

```
Xft.dpi: 100
```

Setting different values should result in different scaling factors.  Please re-open the issue if this doesn't work for you.

**Comment by QuinnFreedman** [comment]
When I was using plain i3-gaps, setting `Xft.dpi` in my  `~/.Xresources` worked perfectly. But, when I installed Regolith, it stopped working. I set the same DPI in `~/.Xresources` and `~/.Xresources-regolith`  (180) and it did change the scaling of the i3 bar, but nothing else.

When I go into the gnome settings in Regolith (`$mod+d`) I can set the display scaling to be 100% or 200%. This does effect *most* apps (although not all, like Alacritty and Rofi) but there is no way to set it to be 150% or 175%, which is where I would like it. Setting `xranr --dpi` didn't do anything either.

**Comment by JMY1000** [comment]
Pretty much the same boat as @QuinnFreedman right now.

**Comment by kgilmer** [comment]
There may be some tips here: https://wiki.gnome.org/HowDoI/HiDpi and here https://wiki.archlinux.org/index.php/HiDPI#GNOME.

**Comment by JMY1000** [comment]
I think the biggest offender right now is st, which doesn't respect Gnome scaling at all and instead requires the font sized to be changed in the Xresources. For now I'm back to xterm/Gnome terminal.
